version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: ~/jopijs
restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
      - v3-dependencies-{{ checksum "package.json" }}
      - v3-dependencies-
save_modules_cache: &save_modules_cache
  save_cache:
    paths:
      - ./node_modules
    key: v3-dependencies-{{ checksum "package.json" }}

jobs:
  Check_Build_Test:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_modules_cache
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Link dependencies
          command: |
            npm run bootstrap
      - run:
          name: Build packages and test
          command: |
            npm test
      - <<: *save_modules_cache
  Deliver_Deploy:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_modules_cache
      - add_ssh_keys:
          fingerprints:
            - 'df:0b:f7:bf:63:60:b1:cb:86:79:2e:73:f9:8a:7d:26'
      - run:
          name: GH user
          command: |
            git config --global user.email $GITHUB_EMAIL && git config --global user.name $GITHUB_USER
      - run:
          name: Create new version
          command: |
            $(yarn bin)/lerna version patch --yes
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/jopijs/.npmrc
      - run:
          name: Publish package
          command: $(yarn bin)/lerna publish from-package --yes
      - <<: *save_modules_cache
workflows:
  version: 2
  Lerna:
    jobs:
      - Check_Build_Test
      - Deliver_Deploy:
          filters:
            branches:
              only: development
          requires:
            - Check_Build_Test
