name: Integration tests

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build Jopi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Installing yarn
        run: yarn install

      - name: Test
        run: yarn test

      - name: Run coverage
        run: yarn jest --coverage

      - name: Build Jopi
        run: yarn build
